### ISSUE TITLE
Bug with hazzard detection and branches on pipeline.cpu and pipeline-extended.cpu

### ISSUE THREAD

**Issue by andrewparlane** [brunonova/drmips#10]
Try running the following code (it should be .asm but github doesn't allow uploading .asm files) on both the unicycle.cpu and the pipeline.cpu (it takes about 600 / 700 cycles to finish). Note the differences in the data memory.

[qsort.txt](https://github.com/brunonova/drmips/files/2324604/qsort.txt)

I have a fix for this here: https://github.com/andrewparlane/drmips/commit/f87671b6d7d456f38ca9662d7b7037388e0f2693

I'll create a pull request once I've finished off my project and can create all the pull requests at once.

**Comment by brunonova** [comment]
Nice find! I'll way for your pull requests.
