### ISSUE TITLE
Distribute self-contained executable jar

### ISSUE THREAD

**Issue by TheThirdOne** [brunonova/drmips#7]
Neither of the distributions for PC seem ideal to me, the .exe is not ideal because it means running an untrusted binary and the .zip is not ideal because it is not clear what is in it before downloading. 

A self-contained executable jar seems better to me then either of the current options. I haven't worked with packaging executable jars for a while, but it shouldn't be too hard to package the PC version as a single executable jar. Was it considered? And if it was and rejected, why was it not used?

**Comment by brunonova** [comment]
If you're worried about running untrusted .exe files from the Internet - and you definitely should be - you should also be worried about running untrusted .jar files. They can do the same kind of damage as .exe files.

The .exe file is an installer created with InnoSetup, which includes the .jar file packaged into a .exe file by Launch4j. I created it mostly for convenience.

The .zip file is an archive that contains the .jar file, plus all supporting files. These files either must be outside the jar (documentation, so the browser can open it), or they are better outside (so the user can modify them).
There are no .exe files here.

**Comment by TheThirdOne** [comment]
> you should also be worried about running untrusted .jar files. They can do the same kind of damage as .exe files.

The main difference to me is that it is much easier to audit a jar file.

> These files either must be outside the jar (documentation, so the browser can open it), or they are better outside (so the user can modify them).

I hadn't considered this; definitely a valid reason to prefer those files outside the jar. 

Thanks for your quick response.

**Comment by brunonova** [comment]
> The main difference to me is that it is much easier to audit a jar file.

That is true.
