### ISSUE TITLE
shamt

### ISSUE THREAD

**Issue by mfacundo94** [brunonova/drmips#8]
How can I make use of the SHAMT? Cause I need to add SLL. Already tried to do so in the json file, with all the correct opcodes and values but i dont know how to take the shamt parameter

**Comment by brunonova** [comment]
I don't know how the `SLL` instruction is supposed to be implemented.

From what I read, it seems the `SHAMT` field should be passed from the instruction to the ALU in another input. So, the code of the ALU component would need to be modified to receive that input.
You could create a custom ALU component class that receives this input and handles shifts, as described [here][doc]. This class would extend the ALU class.

You would then need to modify the datapath in the JSON file to pass the `SHAMT` field to the new input of this custom ALU.
You would also need to modify the JSON file of the instruction set to add the `SLL` instruction and update the `alu` section accordingly.

[doc]: https://cdn.rawgit.com/brunonova/drmips/v2.0.1/doc/manuals/en/configuration.html#custom_comps
